[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[font]
size = 16

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
decorations = "none"

[window.padding]
x = 10
y = 15


[keyboard]



